project:
  type: website
  output-dir: docs
  pre-render:
    - _pre-set-updated.py

website:
  title: "DSAN 5500"
  favicon: favicon.png
  repo-url: "https://github.com/jpowerj/dsan5500"
  repo-actions: [source]
  repo-link-target: "_blank"
  sidebar:
    title: "DSAN 5500: Data Structures, Objects, and Algorithms in Python"
    id: mainnav
    footer: "*Updated {{< env DSAN5500_LAST_UPDATED \"2026-01-08\" >}}*"
    contents:
      - text: "<i class='bi bi-house pe-1'></i> Home"
        href: index.qmd
      - text: "Syllabus"
        href: syllabus.qmd
      - text: "Resources"
        href: resources.qmd
      - text: "Assignments"
        href: assignments.qmd
      - text: "Midterm"
        href: midterm.qmd
      - text: "Final Project"
        href: final.qmd
      - text: "Extra Writeups"
        href: writeups/index.qmd
      - text: "Labs / Demos"
        href: labs/index.qmd
      - "---"
      - text: "Zoom Link <i class='bi bi-box-arrow-up-right ps-1'></i>"
        href: "https://georgetown.zoom.us/j/96890677659?pwd=Fi424zzFfUnhOQIJwb66Zm2EAnzs0s.1"
        target: "_blank"
      - text: "Recordings <i class='bi bi-box-arrow-up-right ps-1'></i>"
        href: "https://georgetown.hosted.panopto.com/Panopto/Pages/Sessions/List.aspx?folderID=928f1543-6867-4fd4-92b5-b3c3017976e4"
        target: "_blank"
      - "---"
      - text: "Week 1: {{< var w01.date-md >}}"
        href: "w01/index.qmd"
      - text: "Week 2: {{< var w02.date-md >}}"
        href: "w02/index.qmd"
      - text: "Week 3: {{< var w03.date-md >}}"
        href: "w03/index.qmd"
      - text: "Week 4: {{< var w04.date-md >}}"
        href: "w04/index.qmd"
      - text: "Week 5: {{< var w05.date-md >}}"
        href: "w05/index.qmd"
      - text: "Week 6: {{< var w06.date-md >}}"
        href: "w06/index.qmd"
      - text: "Week 7: {{< var w07.date-md >}}"
        href: "w07/index.qmd"
      - text: "Week 8: {{< var w08.date-md >}}"
        href: "w08/index.qmd"
      - text: "Week 9: {{< var w09.date-md >}}"
        href: "w09/index.qmd"
      - text: "Week 10: {{< var w10.date-md >}}"
        href: "w10/index.qmd"
      - text: "Week 11: {{< var w11.date-md >}}"
        href: "w11/index.qmd"
      - text: "Week 12: {{< var w12.date-md >}}"
        href: "w12/index.qmd"
      - text: "Week 13: {{< var w13.date-md >}}"
        href: "w13/index.qmd"
      - text: "Week 14: {{< var w14.date-md >}}"
        href: "w14/index.qmd"
      - "---"
      - text: "Google Classroom <i class='bi bi-box-arrow-up-right ps-1'></i>"
        href: "https://classroom.google.com/c/ODM3MzMwODU5ODY0?cjc=f6acpnqr"
        target: "_blank"
      - text: "Google Space <i class='bi bi-box-arrow-up-right ps-1'></i>"
        href: "https://chat.google.com/room/AAQA9C0-Gtc?cls=7"
        target: "_blank"
      - text: "Anonymous Feedback <i class='bi bi-box-arrow-up-right ps-1'></i>"
        href: "https://forms.gle/3yXRNm4m7q5b8kN76"
        target: "_blank"

format:
  html:
    theme:
      light: [default, "./dsan-globals/jjquarto.scss"]
      dark: [darkly, "./dsan-globals/jjquarto.scss"]
    css: "/dsan-globals/jjstyles.css"
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    include-in-header:
      text: "<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js' integrity='sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==' crossorigin='anonymous' referrerpolicy='no-referrer'></script><link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css'><link rel='stylesheet' type='text/css' href='https://cdn.jsdelivr.net/gh/dreampulse/computer-modern-web-font@master/fonts.css'><script src='/sidebar.js'></script>"
